name: Chrome

'on':
  - push
  - workflow_dispatch

jobs:
  chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Chrome
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          build: npx cypress verify
          start: npx cypress run --browser chrome --record --key 73d9e387-617b-4f87-9dea-fa3f20d72fb9
          browser: chrome